
let D={students:[],teachers:[],attendance:[],teacherAttendance:[],homework:[],templates:[],results:[],fees:[]};
const $=id=>document.getElementById(id), uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7), today=()=>new Date().toISOString().slice(0,10);
const get=k=>JSON.parse(localStorage.getItem("v17_"+k)||"[]"), set=(k,v)=>localStorage.setItem("v17_"+k,JSON.stringify(v));
const getObj=k=>JSON.parse(localStorage.getItem("v17_"+k)||"{}"), setObj=(k,v)=>localStorage.setItem("v17_"+k,JSON.stringify(v));
function show(id,b){document.querySelectorAll(".page").forEach(p=>p.classList.remove("show"));$(id).classList.add("show");document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active")}
function norm(n){n=String(n||"").replace(/\D/g,""); if(n.length==10)n="91"+n; return n}
function valid(n){return /^91[0-9]{10}$/.test(norm(n))}
window.onload=()=>{attDate.value=tAttDate.value=hwDate.value=feeDate.value=today();seedTpl();loadAll();loadSettings();}
function loadAll(){Object.keys(D).forEach(k=>D[k]=get(k));render();}
function render(){studentCount.innerText=D.students.length;teacherCount.innerText=D.teachers.length;todayPresent.innerText=D.attendance.filter(a=>a.date==today()&&a.status=="Present").length;renderStudents();renderTeachers();renderTpl();renderResults();renderFees();}
function clearStudent(){["sId","sName","sDivision","sRoll","sParent","sMother","sAadhar","sUdise","sDob","sAddress"].forEach(i=>$(i).value="")}
function saveStudent(){if(!sName.value)return alert("विद्यार्थी नाव टाका"); if(!valid(sParent.value))return alert("मोबाईल 917507514475 या स्वरूपात टाका");let id=sId.value||uid(), a=D.students, i=a.findIndex(x=>x.id==id);let o={id,name:sName.value,className:sClass.value,division:sDivision.value,roll:sRoll.value,parent:norm(sParent.value),mother:sMother.value,aadhar:sAadhar.value,udise:sUdise.value,dob:sDob.value,address:sAddress.value,photo:sPhoto.files[0]?sPhoto.files[0].name:""};i>=0?a[i]=o:a.push(o);set("students",a);clearStudent();loadAll();alert("Student Save झाला")}
function renderStudents(){let q=(studentSearch?.value||"").toLowerCase();let rows=D.students.filter(s=>(s.name||"").toLowerCase().includes(q)||String(s.parent||"").includes(q));studentTable.innerHTML="<tr><th>नाव</th><th>वर्ग</th><th>रोल</th><th>WhatsApp</th><th>Action</th></tr>"+rows.map(s=>`<tr><td>${s.name}</td><td>${s.className}</td><td>${s.roll}</td><td>${s.parent}</td><td><button class='small' onclick='editStudent("${s.id}")'>Edit</button> <button class='bad small' onclick='deleteRow("students","${s.id}")'>Delete</button></td></tr>`).join("")}
function editStudent(id){let s=D.students.find(x=>x.id==id);["sId","sName","sDivision","sRoll","sParent","sMother","sAadhar","sUdise","sDob","sAddress"].forEach(i=>{});sId.value=s.id;sName.value=s.name;sClass.value=s.className;sDivision.value=s.division||"";sRoll.value=s.roll||"";sParent.value=s.parent;sMother.value=s.mother||"";sAadhar.value=s.aadhar||"";sUdise.value=s.udise||"";sDob.value=s.dob||"";sAddress.value=s.address||""}
function clearTeacher(){["tId","tName","tMobile","tSubject","tJoin","tSalary","tUser","tPass"].forEach(i=>$(i).value="")}
function saveTeacher(){if(!tName.value)return alert("शिक्षक नाव टाका"); if(!valid(tMobile.value))return alert("मोबाईल 91XXXXXXXXXX स्वरूपात टाका");let id=tId.value||uid(),a=D.teachers,i=a.findIndex(x=>x.id==id);let o={id,name:tName.value,mobile:norm(tMobile.value),subject:tSubject.value,className:tClass.value,join:tJoin.value,salary:tSalary.value,user:tUser.value,pass:tPass.value};i>=0?a[i]=o:a.push(o);set("teachers",a);clearTeacher();loadAll();alert("Teacher Save झाला")}
function renderTeachers(){teacherTable.innerHTML="<tr><th>नाव</th><th>WhatsApp</th><th>विषय</th><th>वर्ग</th><th>Action</th></tr>"+D.teachers.map(t=>`<tr><td>${t.name}</td><td>${t.mobile}</td><td>${t.subject}</td><td>${t.className}</td><td><button class='bad small' onclick='deleteRow("teachers","${t.id}")'>Delete</button></td></tr>`).join("")}
function deleteRow(k,id){if(confirm("Delete करायचे?")){D[k]=D[k].filter(x=>x.id!=id);set(k,D[k]);loadAll()}}
function loadAttendance(){attList.innerHTML=D.students.filter(s=>s.className==attClass.value).map(s=>`<div class='row' data-id='${s.id}' data-status='Present'><b>${s.roll||""} ${s.name}</b><button class='ok' onclick="mark(this,'Present')">उपस्थित</button><button class='bad' onclick="mark(this,'Absent')">अनुपस्थित</button><button class='half' onclick="mark(this,'Half Day')">अर्धा दिवस</button><span class='st'>Present</span></div>`).join("")||"विद्यार्थी नाहीत"}
function mark(btn,st){let r=btn.closest(".row");r.dataset.status=st;r.querySelector(".st").innerText=st}
function saveAttendance(){let a=D.attendance;document.querySelectorAll("#attList .row").forEach(r=>{let s=D.students.find(x=>x.id==r.dataset.id);a.push({date:attDate.value,className:attClass.value,name:s.name,mobile:s.parent,status:r.dataset.status})});set("attendance",a);loadAll();alert("Attendance Save झाली")}
function loadTeacherAttendance(){tAttList.innerHTML=D.teachers.map(t=>`<div class='row' data-id='${t.id}' data-status='Present'><b>${t.name}</b><button class='ok' onclick="mark(this,'Present')">उपस्थित</button><button class='bad' onclick="mark(this,'Absent')">अनुपस्थित</button><button class='half' onclick="mark(this,'Leave')">रजा</button><span class='st'>Present</span></div>`).join("")||"शिक्षक नाहीत"}
function saveTeacherAttendance(){let a=D.teacherAttendance;document.querySelectorAll("#tAttList .row").forEach(r=>{let t=D.teachers.find(x=>x.id==r.dataset.id);a.push({date:tAttDate.value,name:t.name,mobile:t.mobile,status:r.dataset.status})});set("teacherAttendance",a);loadAll();alert("Teacher Attendance Save झाली")}
function loadHomeworkList(){hwList.innerHTML=D.students.filter(s=>s.className==hwClass.value).map(s=>`<label class='row'><b>${s.name}</b><span>${s.parent}</span><input type='checkbox' data-name='${s.name}' data-mobile='${s.parent}'> गृहपाठ केला नाही</label>`).join("")||"विद्यार्थी नाहीत"}
function saveHomework(){let notDone=[...document.querySelectorAll("#hwList input:checked")].map(x=>({name:x.dataset.name,mobile:x.dataset.mobile}));D.homework.push({id:uid(),date:hwDate.value,className:hwClass.value,subject:hwSubject.value,classwork:classwork.value,homework:homeworkText.value,link:hwLink.value,notDone});set("homework",D.homework);loadAll();alert("Homework Save झाला")}
const def={"अनुपस्थिती":{mr:"आदरणीय पालक, आपला पाल्य {student} आज अनुपस्थित आहे.",hi:"आदरणीय अभिभावक, आपका विद्यार्थी {student} आज अनुपस्थित है.",en:"Your child {student} is absent today."},"गृहपाठ केला नाही":{mr:"आपल्या पाल्याने आज गृहपाठ केलेला नाही. कृपया लक्ष द्यावे.",hi:"आपके विद्यार्थी ने आज गृहकार्य नहीं किया है.",en:"Homework not completed."},"फी सूचना":{mr:"कृपया शालेय फी वेळेत जमा करावी.",hi:"कृपया विद्यालय शुल्क समय पर जमा करें.",en:"Please pay school fee."},"परीक्षा सूचना":{mr:"परीक्षेची तयारी करून विद्यार्थ्यांना वेळेत पाठवावे.",hi:"परीक्षा हेतु विद्यार्थी को समय पर भेजें.",en:"Exam notice."},"निकाल सूचना":{mr:"निकाल पत्रक तयार आहे.",hi:"रिजल्ट तैयार है.",en:"Result is ready."},"पालक सभा":{mr:"पालक सभा आयोजित आहे. कृपया उपस्थित राहावे.",hi:"अभिभावक बैठक आयोजित है.",en:"Parent meeting notice."},"सुट्टी सूचना":{mr:"शाळेला सुट्टी राहील.",hi:"विद्यालय में अवकाश रहेगा.",en:"Holiday notice."},"शैक्षणिक कार्यक्रम":{mr:"शैक्षणिक कार्यक्रम आयोजित करण्यात आला आहे.",hi:"शैक्षणिक कार्यक्रम आयोजित है.",en:"Academic program notice."},"क्रीडा कार्यक्रम":{mr:"क्रीडा कार्यक्रमासाठी विद्यार्थी उपस्थित राहावेत.",hi:"खेल कार्यक्रम हेतु विद्यार्थी उपस्थित रहें.",en:"Sports notice."},"सहल सूचना":{mr:"शैक्षणिक सहलीबाबत सूचना.",hi:"शैक्षणिक यात्रा संबंधी सूचना.",en:"Tour notice."},"वाढदिवस शुभेच्छा":{mr:"वाढदिवसाच्या हार्दिक शुभेच्छा!",hi:"जन्मदिन की शुभकामनाएँ!",en:"Happy Birthday!"},"शिस्त सूचना":{mr:"आपल्या पाल्याच्या शिस्तीसंदर्भात शाळेशी संपर्क साधावा.",hi:"विद्यार्थी के अनुशासन संबंधी विद्यालय से संपर्क करें.",en:"Please contact school regarding discipline."},"सामान्य सूचना":{mr:"शाळेची महत्त्वाची सूचना.",hi:"विद्यालय की महत्वपूर्ण सूचना.",en:"Important school notice."}};
function seedTpl(){if(!get("templates").length){let a=[];Object.keys(def).forEach(t=>["mr","hi","en"].forEach(l=>a.push({id:uid(),type:t,lang:l,text:def[t][l]})));set("templates",a)}}
function fillTpl(){if(tplType.value)tplText.value=(def[tplType.value]||{})[tplLang.value]||""}
function saveTemplate(){if(!tplType.value||!tplText.value)return alert("Template निवडा");D.templates.push({id:uid(),type:tplType.value,lang:tplLang.value,text:tplText.value});set("templates",D.templates);loadAll();alert("Template Save झाले")}
function renderTpl(){tplTable.innerHTML="<tr><th>Type</th><th>Lang</th><th>Text</th></tr>"+D.templates.map(t=>`<tr><td>${t.type}</td><td>${t.lang}</td><td>${t.text}</td></tr>`).join("")}
function api(){let o=getObj("api");return {base:apiBase.value||o.base||"https://whatsbot.tech/api",token:apiToken.value||o.token||"",device:deviceId.value||o.device||"46120",mobile:norm(defaultWhatsApp.value||o.mobile||"917507514475")}}
function saveApiSettings(){setObj("api",api());alert("WhatsApp API Settings Save झाले")}
function makeTextUrl(m,msg){let o=api();return `${o.base}/send_sms?api_token=${encodeURIComponent(o.token)}&mobile=${norm(m)}&message=${encodeURIComponent(msg)}&device_id=${encodeURIComponent(o.device)}`}
function sendTextMessage(){let u=makeTextUrl(defaultWhatsApp.value,testMessage.value);generatedUrl.value=u; fetch(u).then(r=>r.text()).then(x=>alert("Response: "+x)).catch(e=>alert("URL Generated. Browser CORS/Token तपासा."))}
function sendTemplateToAll(){let txt=tplText.value||"School Notice";bulkUrls.value=D.students.map(s=>makeTextUrl(s.parent,txt.replaceAll("{student}",s.name))).join("\\n");alert("सर्व पालकांसाठी URL Generate झाले")}
function sendAbsentMessages(){let abs=D.attendance.filter(a=>a.date==attDate.value&&a.status=="Absent");bulkUrls.value=abs.map(a=>makeTextUrl(a.mobile,`आदरणीय पालक, आपला पाल्य ${a.name} आज अनुपस्थित आहे.`)).join("\\n");alert("Absent message URLs generated")}
function sendHomeworkNotDone(){let last=D.homework[D.homework.length-1];if(!last)return alert("Homework save करा");bulkUrls.value=last.notDone.map(s=>makeTextUrl(s.mobile,`आपल्या पाल्याने आज ${last.subject} विषयाचा गृहपाठ केलेला नाही.`)).join("\\n");alert("Homework not done URLs generated")}
function generateMediaUrl(){let o=api(),mob=norm(mediaMobile.value),ep=mediaType.value,key=ep=="send_img"?"img_url":ep=="send_doc"?"doc_url":ep=="send_video"?"video_url":"audio_url";let cap=ep=="send_img"?"img_caption":ep=="send_audio"?"audio_title":"caption";mediaGeneratedUrl.value=`${o.base}/${ep}?api_token=${encodeURIComponent(o.token)}&mobile=${mob}&${key}=${encodeURIComponent(mediaUrl.value)}&${cap}=${encodeURIComponent(mediaCaption.value)}&device_id=${encodeURIComponent(o.device)}`}
function sendMedia(){generateMediaUrl();fetch(mediaGeneratedUrl.value).then(r=>r.text()).then(x=>alert("Response: "+x)).catch(e=>alert("URL Generated. Public URL/API token तपासा."))}
function saveResult(){let marks=resMarks.value, total=0, count=0;marks.split(",").forEach(p=>{let v=Number((p.split(":")[1]||"").trim());if(v){total+=v;count++}});let pct=count?Math.round(total/count):0;D.results.push({id:uid(),exam:resExam.value,className:resClass.value,name:resName.value,roll:resRoll.value,marks,percentage:pct,grade:pct>=75?"A":pct>=60?"B":pct>=45?"C":"D",remark:resRemark.value});set("results",D.results);loadAll();alert("Result Save झाला")}
function renderResults(){resTable.innerHTML="<tr><th>Exam</th><th>Class</th><th>Name</th><th>Marks</th><th>%</th><th>Grade</th></tr>"+D.results.map(r=>`<tr><td>${r.exam}</td><td>${r.className}</td><td>${r.name}</td><td>${r.marks}</td><td>${r.percentage}</td><td>${r.grade}</td></tr>`).join("")}
function printResultCard(){let r=D.results[D.results.length-1];if(!r)return alert("Result save करा");resultPrint.innerHTML=`<div class='resultcard'><h2>${schoolTitle.innerText}</h2><h2>निकाल पत्रक</h2><p>विद्यार्थी: <b>${r.name}</b> | वर्ग: ${r.className} | रोल: ${r.roll}</p><p>परीक्षा: ${r.exam}</p><p>गुण: ${r.marks}</p><p>टक्केवारी: ${r.percentage}% | Grade: ${r.grade}</p><p>Remark: ${r.remark||""}</p></div>`;window.print()}
function sendResultWhatsApp(){let r=D.results[D.results.length-1];if(!r)return alert("Result save करा");let s=D.students.find(x=>x.name==r.name);if(!s)return alert("विद्यार्थी student list मध्ये शोधला नाही");generatedUrl.value=makeTextUrl(s.parent,`निकाल: ${r.name}, ${r.exam}, गुण: ${r.marks}, टक्केवारी ${r.percentage}%, Grade ${r.grade}`);alert("Result WhatsApp URL generated")}
function saveFee(){let total=Number(feeTotal.value||0), paid=Number(feePaid.value||0);D.fees.push({id:uid(),className:feeClass.value,student:feeStudent.value,total,paid,balance:total-paid,date:feeDate.value,remark:feeRemark.value});set("fees",D.fees);loadAll();alert("Fee Save झाली")}
function renderFees(){feeTable.innerHTML="<tr><th>Class</th><th>Student</th><th>Total</th><th>Paid</th><th>Balance</th></tr>"+D.fees.map(f=>`<tr><td>${f.className}</td><td>${f.student}</td><td>${f.total}</td><td>${f.paid}</td><td>${f.balance}</td></tr>`).join("")}
function sendFeePending(){bulkUrls.value=D.fees.filter(f=>Number(f.balance)>0).map(f=>{let s=D.students.find(x=>x.name==f.student);return s?makeTextUrl(s.parent,`कृपया थकीत फी ₹${f.balance} जमा करावी.`):""}).join("\\n");alert("Pending fee URLs generated")}
function showReport(){let rows=D[reportType.value]||[];reportBox.innerHTML="<table><tr>"+(rows[0]?Object.keys(rows[0]).map(h=>`<th>${h}</th>`).join(""):"")+"</tr>"+rows.map(r=>"<tr>"+Object.values(r).map(v=>`<td>${Array.isArray(v)?JSON.stringify(v):v}</td>`).join("")+"</tr>").join("")+"</table>"}
function xlsx(name,rows){let ws=XLSX.utils.json_to_sheet(rows);let wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Report");XLSX.writeFile(wb,name)}
function download(k,name){xlsx(name,D[k]||[])}function downloadReport(){download(reportType.value,reportType.value+".xlsx")}
function makeAiDraft(){let t=aiType.value, c=aiClass.value||"विद्यार्थी", s=aiSubject.value||"", m=aiInput.value||"";aiOutput.value=`सर्व पालकांना सूचित करण्यात येते की, ${c} ${s} संदर्भात ${m} ही महत्त्वाची सूचना आहे. कृपया आपल्या पाल्याला आवश्यक तयारीसह शाळेत पाठवावे.\\n\\n- मुख्याध्यापक`;}
function saveGeneral(){let g={school:setSchool.value,address:setAddress.value,year:setYear.value,user:adminUser.value,pass:adminPass.value};setObj("general",g);loadSettings();alert("Settings Save झाले")}
function loadSettings(){let a=getObj("api");apiBase.value=a.base||"https://whatsbot.tech/api";apiToken.value=a.token||"";deviceId.value=a.device||"46120";defaultWhatsApp.value=a.mobile||"917507514475";mediaMobile.value=a.mobile||"917507514475";let g=getObj("general");if(g.school)schoolTitle.innerText=g.school;if(g.address)schoolAddressTitle.innerText=g.address;if(g.year)academicYear.innerText=g.year;setSchool.value=g.school||"";setAddress.value=g.address||"";setYear.value=g.year||"शैक्षणिक वर्ष 2025 - 26";adminUser.value=g.user||"";adminPass.value=g.pass||""}
function backupData(){let data={D,api:getObj("api"),general:getObj("general")};let blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});let a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="school_erp_backup.json";a.click()}
async function restoreData(){let f=restoreFile.files[0];if(!f)return alert("Backup JSON निवडा");let data=JSON.parse(await f.text());Object.keys(data.D||{}).forEach(k=>set(k,data.D[k]));if(data.api)setObj("api",data.api);if(data.general)setObj("general",data.general);loadAll();loadSettings();alert("Restore पूर्ण झाले")}
