let D={students:[],attendance:[],homework:[],results:[],fees:[],health:[],distribution:[],library:[],committees:[],transport:[],mdm:[],users:[],teachers:[],photos:[],audit:[]};
const $=id=>document.getElementById(id), uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7), today=()=>new Date().toISOString().slice(0,10);
const get=k=>JSON.parse(localStorage.getItem('v32_'+k)||'[]'), set=(k,v)=>localStorage.setItem('v32_'+k,JSON.stringify(v)), getO=k=>JSON.parse(localStorage.getItem('v32_'+k)||'{}'), setO=(k,v)=>localStorage.setItem('v32_'+k,JSON.stringify(v));
function show(id,b){document.querySelectorAll('.page').forEach(p=>p.classList.remove('show'));$(id).classList.add('show');document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderAll()}
window.onload=()=>{['attDate','mdmDate'].forEach(i=>{$(i)&&($(i).value=today())});loadAll();loadSettings();seedTemplates(false)}
function loadAll(){Object.keys(D).forEach(k=>D[k]=get(k));renderAll()}
function renderAll(){studentCount&&(studentCount.innerText=D.students.length);attToday&&(attToday.innerText=D.attendance.filter(a=>a.date==today()).length);feeDue&&(feeDue.innerText=D.fees.reduce((s,f)=>s+(+f.balance||0),0));refreshSelects();renderStudents();renderAttendanceTable();['users','teachers','homework','results','fees','health','distribution','library','committees','transport','mdm','audit'].forEach(renderTable)}
function refreshSelects(){let opts=D.students.map(s=>`<option value="${s.id}">${s.roll}. ${s.name} - ${s.className}</option>`).join('');['certStudent','resStudent','feeStudent','healthStudent','distStudent','bookStudent','photoStudent'].forEach(i=>{if($(i))$(i).innerHTML=opts}); if(window.templateKey){let t=getO('templates'); templateKey.innerHTML=Object.keys(t).map(k=>`<option value="${k}">${k}</option>`).join('')}}
function studentBy(id){return D.students.find(x=>x.id==id)||{}}
function loadSampleStudents(){D.students=(window.SEED_STUDENTS||[]).map(s=>({...s,id:s.id||uid()}));set('students',D.students);renderAll();alert('मागची 34 विद्यार्थ्यांची यादी Import झाली')}
function seedTemplates(showAlert=true){if(!Object.keys(getO('templates')).length)setO('templates',window.DEFAULT_TEMPLATES||{});refreshSelects();if(showAlert)alert('Templates Import झाले')}
function fill(t,o){return (t||'').replace(/\{(\w+)\}/g,(m,k)=>o[k]??m)}
function saveStudent(){D.students.push({id:uid(),admissionNo:sAdmission.value,name:sName.value,mother:sMother.value,className:sClass.value,roll:sRoll.value,religion:sReligion.value,caste:sCaste.value,dob:sDob.value,admissionDate:sAdmissionDate.value,parent:sParent.value});set('students',D.students);renderAll()}
function renderStudents(){if(!window.studentTable)return;studentTable.innerHTML='<tr><th>रोल</th><th>प्रवेश</th><th>नाव</th><th>आई</th><th>धर्म</th><th>जात</th><th>DOB</th><th>Mobile</th></tr>'+D.students.map(s=>`<tr><td>${s.roll||''}</td><td>${s.admissionNo||''}</td><td>${s.name||''}</td><td>${s.mother||''}</td><td>${s.religion||''}</td><td>${s.caste||''}</td><td>${s.dob||''}</td><td>${s.parent||''}</td></tr>`).join('')}
function loadAttendance(){attList.innerHTML=D.students.filter(s=>s.className==attClass.value).map(s=>`<div class='row' data-id='${s.id}' data-status='P'><b>${s.roll}</b><b>${s.name}<br><small>${s.mother||''}</small></b><button class='ok' onclick="mark(this,'P')">P</button><button class='bad' onclick="mark(this,'A')">A</button><button class='half' onclick="mark(this,'H')">H</button><button class='late' onclick="mark(this,'L')">L</button><span class='st'>P</span></div>`).join('')}
function mark(btn,st){let r=btn.closest('.row');r.dataset.status=st;r.querySelector('.st').innerText=st;let s=studentBy(r.dataset.id), t=getO('templates')['attendance_'+st]||'{STUDENT} {STATUS}';let msg=fill(t,{STUDENT:s.name,DATE:attDate.value,CLASS:s.className,STATUS:st});msgUrls.value=(msgUrls.value?msgUrls.value+'\n':'')+buildWhatsUrl(s.parent,msg)+'\n'+buildApiUrl(s.parent,msg)}
function saveAttendance(){let date=attDate.value;D.attendance=D.attendance.filter(a=>!(a.date==date&&a.className==attClass.value));document.querySelectorAll('#attList .row').forEach(r=>{let s=studentBy(r.dataset.id);D.attendance.push({date,className:attClass.value,roll:s.roll,name:s.name,mother:s.mother,mobile:s.parent,status:r.dataset.status})});set('attendance',D.attendance);renderAll();alert('Attendance Save झाली')}
function buildWhatsUrl(mobile,msg){return `https://wa.me/${mobile||'917507514475'}?text=${encodeURIComponent(msg)}`}
function buildApiUrl(mobile,msg){let w=getO('wa');return `${(w.url||'https://whatsbot.tech/api').replace(/\/$/,'')}/send_sms?api_token=${encodeURIComponent(w.token||'')}&mobile=${encodeURIComponent(mobile||w.mobile||'917507514475')}&message=${encodeURIComponent(msg)}&device_id=${encodeURIComponent(w.device||'')}`}
function generateAttendanceUrls(){let t=getO('templates');msgUrls.value=D.attendance.filter(a=>a.date==attDate.value&&a.className==attClass.value).map(a=>{let msg=fill(t['attendance_'+a.status]||'{STUDENT} attendance {STATUS}',{STUDENT:a.name,DATE:a.date,STATUS:a.status,CLASS:a.className});return buildWhatsUrl(a.mobile,msg)+'\n'+buildApiUrl(a.mobile,msg)}).join('\n')}
function renderAttendanceTable(){if(!window.attendanceTable)return;attendanceTable.innerHTML='<tr><th>Date</th><th>Class</th><th>Roll</th><th>Name</th><th>Status</th><th>Mobile</th></tr>'+D.attendance.slice(-150).map(a=>`<tr><td>${a.date}</td><td>${a.className}</td><td>${a.roll}</td><td>${a.name}</td><td>${a.status}</td><td>${a.mobile}</td></tr>`).join('')}
function saveHomework(){D.homework.push({className:hwClass.value,subject:hwSubject.value,classwork:hwClasswork.value,homework:hwHomework.value,date:today()});set('homework',D.homework);renderAll()}
function homeworkUrls(){let t=getO('templates').homework;hwOut.value=D.students.filter(s=>s.className==hwClass.value).map(s=>buildWhatsUrl(s.parent,fill(t,{CLASS:hwClass.value,SUBJECT:hwSubject.value,CLASSWORK:hwClasswork.value,HOMEWORK:hwHomework.value}))).join('\n')}
function makeCertificate(){let s=studentBy(certStudent.value),g=getO('settings');certBox.innerHTML=`<div class='printbox'><h2>${g.school||schoolTitle.innerText}</h2><h3>${certType.value}</h3><table><tr><th>विद्यार्थी</th><td>${s.name||''}</td></tr><tr><th>आईचे नाव</th><td>${s.mother||''}</td></tr><tr><th>वर्ग</th><td>${s.className||''}</td></tr><tr><th>जन्म दिनांक</th><td>${s.dob||''}</td></tr><tr><th>कारण</th><td>${certReason.value}</td></tr></table><p style='text-align:right;margin-top:45px'>${g.principal||'मुख्याध्यापक'} सही</p></div>`}
function parseMarks(txt){return txt.split(',').map(x=>{let [sub,m]=x.split(':'),[ob,max]=(m||'0/100').split('/');return{sub:(sub||'').trim(),ob:+ob||0,max:+max||100}}).filter(x=>x.sub)}
function saveResult(){let s=studentBy(resStudent.value),ms=parseMarks(resMarks.value),total=ms.reduce((a,b)=>a+b.ob,0),max=ms.reduce((a,b)=>a+b.max,0),pct=max?Math.round(total*100/max):0;D.results.push({student:s.name,mobile:s.parent,exam:resExam.value,marks:resMarks.value,total,max,percentage:pct,grade:pct>=75?'A':pct>=60?'B':pct>=45?'C':'D',attendance:resAttendance.value});set('results',D.results);renderAll()}
function makeResultCard(){let r=D.results[D.results.length-1]||{};resultCard.innerHTML=`<div class='printbox'><h2>निकालपत्र</h2><p>${r.student} - ${r.exam}</p><p>${r.marks}</p><p>${r.total}/${r.max} | ${r.percentage}% | Grade ${r.grade}</p></div>`}
function saveFee(){let s=studentBy(feeStudent.value),total=['feeAdmission','feeTuition','feeExam','feeComputer','feeLibrary','feeTransport','feeOther'].reduce((a,i)=>a+(+$(i).value||0),0),paid=+feePaid.value||0;D.fees.push({student:s.name,mobile:s.parent,total,paid,balance:total-paid,remark:feeRemark.value});set('fees',D.fees);renderAll()}
function makeReceipt(){let f=D.fees[D.fees.length-1]||{};receiptBox.innerHTML=`<div class='printbox'><h2>Fee Receipt</h2><p>${f.student}</p><p>Total ${f.total}, Paid ${f.paid}, Balance ${f.balance}</p></div>`}
function feeReminder(){let t=getO('templates').fees;feeOut.value=D.fees.filter(f=>f.balance>0).map(f=>buildWhatsUrl(f.mobile,fill(t,{STUDENT:f.student,BALANCE:f.balance}))).join('\n')}
function saveHealth(){let s=studentBy(healthStudent.value);D.health.push({student:s.name,height:heightVal.value,weight:weightVal.value,blood:bloodVal.value,hb:hbVal.value,vision:visionVal.value,remark:healthRemark.value});set('health',D.health);renderAll()}
function saveDist(){let s=studentBy(distStudent.value);D.distribution.push({student:s.name,item:distItem.value,qty:distQty.value,details:distDetails.value});set('distribution',D.distribution);renderAll()}
function saveGeneric(k,ids){D[k].push(Object.fromEntries(ids.map(i=>[i,$(i).value])));set(k,D[k]);renderAll()}
function saveGenericStudent(k,sel,ids){let s=studentBy($(sel).value);D[k].push({student:s.name,...Object.fromEntries(ids.map(i=>[i,$(i).value]))});set(k,D[k]);renderAll()}
function renderTable(k){let el=$(k+'Table');if(!el)return;let rows=D[k]||[];el.innerHTML='<tr>'+(rows[0]?Object.keys(rows[0]).map(h=>`<th>${h}</th>`).join(''):'')+'</tr>'+rows.map(r=>'<tr>'+Object.values(r).map(v=>`<td>${v??''}</td>`).join('')+'</tr>').join('')}
function loadTemplateToBox(){templateText.value=(getO('templates')[templateKey.value]||'')}
function saveTemplate(){let t=getO('templates');t[templateKey.value]=templateText.value;setO('templates',t);alert('Template Save झाले')}
function saveWA(){setO('wa',{url:waUrl.value,token:waToken.value,device:waDevice.value,mobile:waMobile.value,smsTemplate:smsTemplate.value});alert('API Save झाला')}
function testWA(){let w=getO('wa'),msg=waMessage.value||'ERP Test';waOut.value=buildWhatsUrl(waMobile.value||w.mobile,msg)+'\n'+buildApiUrl(waMobile.value||w.mobile,msg)}
function openTestWA(){testWA();window.open(waOut.value.split('\n')[0],'_blank')}
function saveFirebase(){setO('firebase',{config:firebaseConfig.value});alert('Firebase Config Save झाले')}
function saveSettings(){let g={school:setSchool.value,address:setAddress.value,year:setYear.value,principal:setPrincipal.value,chairman:setChairman.value,secretary:setSecretary.value,mobile:setMobile.value,logo:setLogo.value};setO('settings',g);loadSettings();alert('Settings Save झाले')}
function loadSettings(){let g=getO('settings');if(g.school)schoolTitle.innerText=g.school;if(g.address)schoolAddressTitle.innerText=g.address;if(g.year)academicYear.innerText=g.year;if(g.logo)document.querySelector('.logoText').style.background=`#fff url('${g.logo}') center/cover no-repeat`;let w=getO('wa');if(window.waUrl){waUrl.value=w.url||'https://whatsbot.tech/api';waToken.value=w.token||'';waDevice.value=w.device||'';waMobile.value=w.mobile||'917507514475';smsTemplate.value=w.smsTemplate||''}}
function showReport(){let rows=D[reportType.value]||[];reportBox.innerHTML='<table><tr>'+(rows[0]?Object.keys(rows[0]).map(h=>`<th>${h}</th>`).join(''):'')+'</tr>'+rows.map(r=>'<tr>'+Object.values(r).map(v=>`<td>${v??''}</td>`).join('')+'</tr>').join('')+'</table>'}
function downloadReport(){let rows=D[reportType.value]||[];let ws=XLSX.utils.json_to_sheet(rows);let wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Report');XLSX.writeFile(wb,reportType.value+'.xlsx')}
function backupData(){let b=new Blob([JSON.stringify({D,settings:getO('settings'),wa:getO('wa'),templates:getO('templates'),firebase:getO('firebase')},null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='school_erp_v32_backup.json';a.click()}
async function restoreData(){let f=restoreFile.files[0];if(!f)return;let data=JSON.parse(await f.text());Object.keys(data.D||{}).forEach(k=>{D[k]=data.D[k];set(k,D[k])});['settings','wa','templates','firebase'].forEach(k=>data[k]&&setO(k,data[k]));loadAll();loadSettings();alert('Restore झाले')}
