let students=[], teachers=[], settings={};
const $=id=>document.getElementById(id);
const today=()=>new Date().toISOString().slice(0,10);
window.onload=async()=>{["saDate","taDate","hwDate"].forEach(id=>$(id).value=today()); await loadSettings(); await loadStudents(); await loadTeachers(); await loadAnswers(); if("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js");};
function show(id,btn){document.querySelectorAll(".page").forEach(p=>p.classList.remove("show"));$(id).classList.add("show");document.querySelectorAll("nav button").forEach(b=>b.classList.remove("active"));btn.classList.add("active");}
function valid(n){return /^[0-9]{10}$/.test(String(n||"").trim());}
async function loadSettings(){let d=await db.collection("settings").doc("main").get();settings=d.exists?d.data():{};Object.keys(settings).forEach(k=>$(k)&&($(k).value=settings[k]||""));if(settings.schoolName) schoolNameTitle.innerText=settings.schoolName;if(settings.schoolAddress) schoolAddressTitle.innerText=settings.schoolAddress;if(settings.logoText) logoPreview.innerText=settings.logoText;}
async function saveSettings(){settings={schoolName:schoolName.value,schoolAddress:schoolAddress.value,proxyUrl:proxyUrl.value,apiToken:apiToken.value,deviceId:deviceId.value,principalMobile:principalMobile.value,presidentMobile:presidentMobile.value,secretaryMobile:secretaryMobile.value,logoText:logoText.value};await db.collection("settings").doc("main").set(settings);await loadSettings();alert("Settings Save झाले");}
async function loadStudents(){let s=await db.collection("students").get();students=s.docs.map(d=>({id:d.id,...d.data()}));countStudents.innerText=students.length;studentTable.innerHTML="<tr><th>नाव</th><th>वर्ग</th><th>पालक मोबाईल</th><th>जन्मदिन</th><th>Action</th></tr>"+students.map(x=>`<tr><td>${x.name||""}</td><td>${x.className||""}</td><td>${x.parentMobile||""}</td><td>${x.dob||""}</td><td><button class='small' onclick='editStudent("${x.id}")'>Edit</button> <button class='bad small' onclick='delDoc("students","${x.id}")'>Delete</button></td></tr>`).join("");}
function clearStudent(){sId.value=sName.value=sParent.value=sDob.value="";}
function editStudent(id){let x=students.find(s=>s.id==id);sId.value=id;sName.value=x.name||"";sClass.value=x.className||"8वी";sParent.value=x.parentMobile||"";sDob.value=x.dob||"";}
async function saveStudent(){if(!sName.value)return alert("विद्यार्थी नाव टाका");if(!valid(sParent.value))return alert("पालक मोबाईल 10 अंकांचा टाका");let data={name:sName.value,className:sClass.value,parentMobile:sParent.value,dob:sDob.value,updatedAt:new Date().toISOString()};if(sId.value) await db.collection("students").doc(sId.value).set(data,{merge:true}); else await db.collection("students").add({...data,createdAt:new Date().toISOString()});clearStudent();loadStudents();}
async function loadTeachers(){let s=await db.collection("teachers").get();teachers=s.docs.map(d=>({id:d.id,...d.data()}));countTeachers.innerText=teachers.length;teacherTable.innerHTML="<tr><th>नाव</th><th>मोबाईल</th><th>विषय</th><th>वर्ग</th><th>User</th><th>Action</th></tr>"+teachers.map(x=>`<tr><td>${x.name||""}</td><td>${x.mobile||""}</td><td>${x.subject||""}</td><td>${x.className||""}</td><td>${x.userId||""}</td><td><button class='small' onclick='editTeacher("${x.id}")'>Edit</button> <button class='bad small' onclick='delDoc("teachers","${x.id}")'>Delete</button></td></tr>`).join("");}
function clearTeacher(){tId.value=tName.value=tMobile.value=tSubject.value=tUser.value=tPass.value="";}
function editTeacher(id){let x=teachers.find(t=>t.id==id);tId.value=id;tName.value=x.name||"";tMobile.value=x.mobile||"";tSubject.value=x.subject||"";tClass.value=x.className||"सर्व";tUser.value=x.userId||"";tPass.value=x.password||"";}
async function saveTeacher(){if(!tName.value)return alert("शिक्षक नाव टाका");if(!valid(tMobile.value))return alert("मोबाईल 10 अंकांचा टाका");let data={name:tName.value,mobile:tMobile.value,subject:tSubject.value,className:tClass.value,userId:tUser.value,password:tPass.value,updatedAt:new Date().toISOString()};if(tId.value) await db.collection("teachers").doc(tId.value).set(data,{merge:true}); else await db.collection("teachers").add({...data,createdAt:new Date().toISOString()});clearTeacher();loadTeachers();}
async function delDoc(c,id){if(confirm("Delete करायचे?")){await db.collection(c).doc(id).delete();loadStudents();loadTeachers();loadAnswers();}}
function mark(btn,status){let r=btn.closest(".row");r.dataset.status=status;r.querySelector("span").innerText=status;}
function loadStudentAttendance(){let cls=saClass.value;studentAttList.innerHTML=students.filter(s=>s.className==cls).map(s=>`<div class="row" data-name="${s.name}" data-mobile="${s.parentMobile}" data-status="Pending"><b>${s.name}</b><button class="ok" onclick="mark(this,'Present')">उपस्थित</button><button class="bad" onclick="mark(this,'Absent')">अनुपस्थित</button><button class="half" onclick="mark(this,'Half Day')">अर्धा दिवस</button><span>Pending</span></div>`).join("")||"विद्यार्थी नाहीत";}
async function saveStudentAttendance(){let rows=[...studentAttList.querySelectorAll(".row")];let p=0,a=0,h=0;for(let r of rows){let st=r.dataset.status;if(st=="Present")p++;if(st=="Absent")a++;if(st=="Half Day")h++;await db.collection("attendance").add({type:"student",date:saDate.value,className:saClass.value,name:r.dataset.name,parentMobile:r.dataset.mobile,status:st,createdAt:new Date().toISOString()});if(st=="Absent")sendMsg(r.dataset.mobile,`आपला पाल्य ${r.dataset.name} आज शाळेत अनुपस्थित आहे.`);if(st=="Half Day")sendMsg(r.dataset.mobile,`आपला पाल्य ${r.dataset.name} आज अर्धा दिवस सुट्टीवर गेला आहे.`);}sendOfficials(`विद्यार्थी उपस्थिती Summary\nवर्ग: ${saClass.value}\nउपस्थित: ${p}\nअनुपस्थित: ${a}\nअर्धा दिवस: ${h}`);alert("Attendance Save झाली");}
function loadTeacherAttendance(){teacherAttList.innerHTML=teachers.map(t=>`<div class="row" data-name="${t.name}" data-status="Pending"><b>${t.name} - ${t.subject||""}</b><button class="ok" onclick="mark(this,'Present')">उपस्थित</button><button class="bad" onclick="mark(this,'Absent')">अनुपस्थित</button><button class="half" onclick="mark(this,'Leave')">रजा</button><span>Pending</span></div>`).join("")||"शिक्षक नाहीत";}
async function saveTeacherAttendance(){let rows=[...teacherAttList.querySelectorAll(".row")];let p=0,a=0,l=0;for(let r of rows){let st=r.dataset.status;if(st=="Present")p++;if(st=="Absent")a++;if(st=="Leave")l++;await db.collection("teacherAttendance").add({date:taDate.value,name:r.dataset.name,status:st,createdAt:new Date().toISOString()});}sendOfficials(`शिक्षक उपस्थिती Summary\nउपस्थित: ${p}\nअनुपस्थित: ${a}\nरजा: ${l}`);alert("Teacher Attendance Save झाली");}
function loadHomeworkStudents(){homeworkList.innerHTML=students.filter(s=>s.className==hwClass.value).map(s=>`<label class="row"><b>${s.name}</b><span>${s.parentMobile}</span><input type="checkbox" data-name="${s.name}" data-mobile="${s.parentMobile}"> गृहपाठ केला नाही</label>`).join("")||"विद्यार्थी नाहीत";}
async function saveHomework(){let nd=[...homeworkList.querySelectorAll("input:checked")];let photo=hwPhoto.files[0]?.name||"";await db.collection("homework").add({date:hwDate.value,className:hwClass.value,subject:hwSubject.value,classWork:classWork.value,homeWork:homeWork.value,link:hwLink.value,photoName:photo,notDone:nd.length,createdAt:new Date().toISOString()});for(let s of students.filter(x=>x.className==hwClass.value))sendMsg(s.parentMobile,`आजचे वर्गकार्य: ${classWork.value}\nगृहपाठ: ${homeWork.value}\nलिंक: ${hwLink.value}`);for(let x of nd)sendMsg(x.dataset.mobile,`सूचना: ${x.dataset.name} यांनी आजचा गृहपाठ पूर्ण केलेला नाही.`);sendOfficials(`गृहपाठ Summary\nवर्ग: ${hwClass.value}\nविषय: ${hwSubject.value}\nगृहपाठ न केलेले: ${nd.length}`);alert("Homework Save झाले");}
async function saveAnswerPhoto(){let f=apFile.files[0];await db.collection("answerPhotos").add({className:apClass.value,student:apStudent.value,subject:apSubject.value,fileName:f?f.name:"",remark:apRemark.value,createdAt:new Date().toISOString()});alert("उत्तरपत्रिका नोंद Save झाली");loadAnswers();}
async function loadAnswers(){let s=await db.collection("answerPhotos").limit(30).get();answerTable.innerHTML="<tr><th>वर्ग</th><th>विद्यार्थी</th><th>विषय</th><th>फोटो नाव</th><th>Remark</th></tr>"+s.docs.map(d=>{let x=d.data();return `<tr><td>${x.className||""}</td><td>${x.student||""}</td><td>${x.subject||""}</td><td>${x.fileName||""}</td><td>${x.remark||""}</td></tr>`}).join("");}
function templateNotice(){let t=noticeType.value;let h=noticeLang.value=="hi";let map={
"शैक्षणिक कार्यक्रमाची सूचना":h?"आदरणीय अभिभावक, विद्यालय में शैक्षणिक कार्यक्रम आयोजित किया गया है। कृपया विद्यार्थी को समय पर भेजें।":"आदरणीय पालक, शाळेत शैक्षणिक कार्यक्रम आयोजित करण्यात आला आहे. कृपया विद्यार्थ्यांना वेळेत पाठवावे.",
"क्रीडा कार्यक्रमाची सूचना":h?"आदरणीय अभिभावक, खेल कार्यक्रम के लिए विद्यार्थी को आवश्यक तैयारी के साथ भेजें।":"आदरणीय पालक, क्रीडा कार्यक्रमासाठी विद्यार्थ्यांना आवश्यक तयारीसह पाठवावे.",
"सुट्टीची सूचना":h?"आदरणीय अभिभावक, विद्यालय में घोषित अवकाश रहेगा।":"आदरणीय पालक, शाळेला घोषित सुट्टी राहील.",
"परीक्षा संदर्भातील सूचना":h?"आदरणीय अभिभावक, परीक्षा संबंधी सूचना: कृपया विद्यार्थी की तैयारी करवाएं।":"आदरणीय पालक, परीक्षा संदर्भात विद्यार्थ्यांची तयारी करून घ्यावी.",
"फी संदर्भातील सूचना":h?"आदरणीय अभिभावक, कृपया विद्यालय शुल्क समय पर जमा करें।":"आदरणीय पालक, कृपया शालेय फी वेळेत जमा करावी.",
"सहली संदर्भातील सूचना":h?"आदरणीय अभिभावक, शैक्षणिक सहल संबंधी सूचना कृपया ध्यान से पढ़ें।":"आदरणीय पालक, शैक्षणिक सहल संदर्भातील सूचना कृपया वाचावी.",
"इतर सूचना":h?"आदरणीय अभिभावक, विद्यालय की महत्वपूर्ण सूचना।":"आदरणीय पालक, शाळेची महत्त्वाची सूचना."
};noticeText.value=map[t];}
async function sendNotice(){if(!noticeText.value)return alert("सूचना मजकूर टाका");for(let s of students)sendMsg(s.parentMobile,noticeText.value);await db.collection("notices").add({type:noticeType.value,message:noticeText.value,lang:noticeLang.value,createdAt:new Date().toISOString()});sendOfficials(`सूचना पाठवली: ${noticeType.value}`);alert("सूचना पालकांना पाठवली");}
async function sendMsg(m,msg){if(!valid(m)||!settings.proxyUrl)return;let url=settings.proxyUrl.replace(/\/$/,"")+`/send_sms?mobile=${m}&message=${encodeURIComponent(msg)}&api_token=${encodeURIComponent(settings.apiToken||"")}&device_id=${encodeURIComponent(settings.deviceId||"")}`;try{await fetch(url)}catch(e){console.log(e)}}
async function sendOfficials(msg){for(let m of [settings.principalMobile,settings.presidentMobile,settings.secretaryMobile]) await sendMsg(m,msg);}
function testMessage(){sendMsg(settings.principalMobile||"7507514475","School ERP V12 Test Message");alert("Test request पाठवली");}
async function uploadExcel(){let f=excelFile.files[0];if(!f)return alert("Excel निवडा");let data=await f.arrayBuffer();let wb=XLSX.read(data);let rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]]);for(let r of rows){if(excelType.value=="students")await db.collection("students").add({name:r.name||r.Name||"",className:r.className||r.Class||"",parentMobile:String(r.parentMobile||r.Mobile||""),dob:r.dob||""});else await db.collection("teachers").add({name:r.name||r.Name||"",mobile:String(r.mobile||r.Mobile||""),subject:r.subject||"",className:r.className||"",userId:r.userId||"",password:r.password||""});}await loadStudents();await loadTeachers();alert("Excel Upload झाले");}
function downloadFile(name,rows){let ws=XLSX.utils.json_to_sheet(rows);let wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Report");XLSX.writeFile(wb,name);}
function downloadStudents(){downloadFile("students_report.xlsx",students);}
function downloadTeachers(){downloadFile("teachers_report.xlsx",teachers);}
async function downloadAttendance(){let s=await db.collection("attendance").get();downloadFile("attendance_report.xlsx",s.docs.map(d=>d.data()));}
async function loadReports(){let s=await db.collection("attendance").limit(50).get();reportBox.innerHTML=s.docs.map(d=>{let x=d.data();return `<p>${x.date||""} - ${x.className||""} - ${x.name||""} - ${x.status||""}</p>`}).join("");}
async function sendDailySummary(){sendOfficials(`Daily Summary: विद्यार्थी ${students.length}, शिक्षक ${teachers.length}. Reports तपासा.`);alert("Daily Summary पाठवली");}